"""Scaffold new plugin or shell directories."""

from __future__ import annotations

import re
from pathlib import Path

PLUGIN_MANIFEST = """plugin_id: {plugin_id}
plugin_type: plugin
version: 0.1.0
api_version: "0.2"
execution:
  mode: local-script
entry: handler:{command}
commands:
  - name: {command}
    target: "TODO: describe target"
verification:
  mode: self_report
"""

PLUGIN_HANDLER = '''"""{plugin_id} plugin handler."""

from __future__ import annotations

from pkg.plugin import HandlerContext, success


def {command}(ctx: HandlerContext):
    return success(ctx, evidence={{"message": "hello from {plugin_id}"}})
'''

SHELL_MANIFEST = """plugin_id: {plugin_id}
plugin_type: shell
version: 0.1.0
api_version: "0.2"
entry: adapter:{class_name}
capabilities:
  inbound_types: [text]
  outbound_types: [text, json]
"""

SHELL_ADAPTER = '''"""{plugin_id} Shell adapter."""

from __future__ import annotations

from typing import Any
from uuid import uuid4


class {class_name}:
    shell_id = "{plugin_id}"

    def to_invoke_request(self, raw: dict[str, Any]) -> dict[str, Any]:
        text = str(raw.get("text") or raw.get("message") or "").strip()
        session_id = str(raw.get("session_id") or f"sess_{{uuid4().hex[:12]}}")
        return {{
            "protocol_version": "1.0.0",
            "request_id": str(raw.get("request_id") or f"req_{{uuid4().hex[:12]}}"),
            "request": {{
                "context": {{
                    "session_id": session_id,
                    "shell_id": self.shell_id,
                    "channel_user_id": str(raw.get("user_id") or session_id),
                    "user_intent": text,
                }}
            }},
        }}

    def from_invoke_response(self, response: dict[str, Any]) -> dict[str, Any]:
        if "error" in response:
            error = response.get("error") or {{}}
            return {{"ok": False, "error": error, "raw": response}}
        directives = (response.get("response") or {{}}).get("action_directives") or []
        text = ""
        if directives:
            text = str((directives[0].get("payload") or {{}}).get("text") or "")
        return {{"ok": True, "reply": text, "raw": response}}
'''

README = """# {plugin_id}

Generated by `deskharness plugin new`.
"""


def _validate_plugin_id(plugin_id: str) -> None:
    if not re.fullmatch(r"[a-z][a-z0-9-]*", plugin_id):
        msg = "plugin_id must match [a-z][a-z0-9-]*"
        raise ValueError(msg)


def _class_name(plugin_id: str) -> str:
    parts = [part.capitalize() for part in plugin_id.replace("_", "-").split("-") if part]
    name = "".join(parts)
    if not name.endswith("Shell"):
        name += "Shell"
    return name


def create_plugin(
    *,
    plugin_id: str,
    plugin_type: str,
    output_dir: Path,
    command: str = "run",
) -> Path:
    _validate_plugin_id(plugin_id)
    root = output_dir / plugin_id
    if root.exists():
        msg = f"target already exists: {root}"
        raise FileExistsError(msg)

    root.mkdir(parents=True)

    if plugin_type == "shell":
        class_name = _class_name(plugin_id)
        (root / "manifest.yaml").write_text(
            SHELL_MANIFEST.format(plugin_id=plugin_id, class_name=class_name),
            encoding="utf-8",
        )
        (root / "adapter.py").write_text(
            SHELL_ADAPTER.format(plugin_id=plugin_id, class_name=class_name),
            encoding="utf-8",
        )
    else:
        (root / "manifest.yaml").write_text(
            PLUGIN_MANIFEST.format(plugin_id=plugin_id, command=command),
            encoding="utf-8",
        )
        (root / "handler.py").write_text(
            PLUGIN_HANDLER.format(plugin_id=plugin_id, command=command),
            encoding="utf-8",
        )

    (root / "README.md").write_text(README.format(plugin_id=plugin_id), encoding="utf-8")
    return root
